language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

# @todo Inotify: on / off
matrix:
  allow_failures:
    - php: nightly
    - php: 7.2
    - php: hhvm-3.9
    - php: hhvm-3.12
    - php: hhvm-3.15
    - php: hhvm-3.18
    - php: hhvm-3.21
  include:
    - php: hhvm-3.9
      dist: trusty
    - php: hhvm-3.12
      dist: trusty
    - php: hhvm-3.15
      dist: trusty
    - php: hhvm-3.18
      dist: trusty
    - php: hhvm-3.21
      dist: trusty
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install: composer install --no-interaction

script:
  - composer test-cl

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ $(phpenv version-name) = "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover test/clover.xml --revision=$TRAVIS_COMMIT; fi
  - if [ $(phpenv version-name) = "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover test/clover.xml --revision=$TRAVIS_COMMIT; fi
  - if [ $(phpenv version-name) = "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover test/clover.xml --revision=$TRAVIS_COMMIT; fi
